### ISSUE TITLE
Inconsistent env variable

### ISSUE THREAD

**Issue by jogobeny** [jcoelho93/python-trading212#1]
Edit
https://github.com/jcoelho93/python-trading212/blob/9194134373fd0d388786b2e0048e77623f9ce3c8/README.md?plain=1#L22
to be consistent with
https://github.com/jcoelho93/python-trading212/blob/9194134373fd0d388786b2e0048e77623f9ce3c8/trading212/trading212.py#L23

**Comment by jcoelho93** [comment]
Fixed

**Comment by jogobeny** [comment]
I think there is still missing `API` substring. @jcoelho93

**Comment by jcoelho93** [comment]
fixed thanks
